[package]

name = "rust-intro"
version = "0.0.1"
authors = ["Caspar Krieger <caspar@asparck.com>"]

[[bin]]
name = "my-rust-intro"

[dependencies.semver]

git = "https://github.com/rust-lang/semver.git"
